version: '3'
services:
  dev5:
    container_name: dev5
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2205:22"
      - "9995:9000"
    networks: 
       SSID:
          ipv4_address: 172.50.0.6
    hostname: dev5
    volumes:
      - /home/tms2744/SSID-new/sandbox4:/purple
    command: python3 /opt/internal.py 5 2 10 5 0
    stdin_open: true
    tty: true
              
  dev4:
    container_name: dev4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2204:22"
      - "9994:9000"
    networks: 
       SSID:
          ipv4_address: 172.50.0.5
    hostname: dev4
    volumes:
      - /home/tms2744/SSID-new/sandbox4:/purple
    command: python3 /opt/internal.py 4 2 10 5 0
    depends_on:
      - dev5
    stdin_open: true
    tty: true
              
  dev3:
    container_name: dev3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2203:22"
      - "9993:9000"
    networks: 
       SSID:
          ipv4_address: 172.50.0.4
    hostname: dev3
    volumes:
      - /home/tms2744/SSID-new/sandbox4:/purple
    command: python3 /opt/internal.py 3 2 10 5 0
    depends_on:
      - dev4
    stdin_open: true
    tty: true
              
  dev2:
    container_name: dev2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2202:22"
      - "9992:9000"
    networks: 
       SSID:
          ipv4_address: 172.50.0.3
    hostname: dev2
    volumes:
      - /home/tms2744/SSID-new/sandbox4:/purple
    command: python3 /opt/internal.py 2 2 10 5 0
    depends_on:
      - dev3
    stdin_open: true
    tty: true
              
  dev1:
    container_name: dev1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2201:22"
      - "9991:9000"
    networks: 
       SSID:
          ipv4_address: 172.50.0.2
    hostname: dev1
    volumes:
      - /home/tms2744/SSID-new/sandbox4:/purple
    command: python3 /opt/internal.py 1 2 10 5 0
    depends_on:
      - dev2
    stdin_open: true
    tty: true
              
volumes:
    purple:
networks:
    SSID:
        ipam:
            driver: default
            config:
                - subnet: 172.50.0.0/24
                  gateway: 172.50.0.254
